### ISSUE TITLE
Admin Page shows no data after logging-in

### ISSUE THREAD

**Issue by asd014** [palinkas-jo-reggelt/hMailServer_2FA#3]
Hi,

I was trying to log in to the admin.php page and was able to log in but it shows blank. Search results return blank as well. Did I miss any configuration? 

I changed config.php.dist to config.php and then replaced all variables. Tried to put this `error_reporting(E_ALL);` at the top of admin.php but no error returned.

![image](https://user-images.githubusercontent.com/87966671/182610446-efdd3a66-fb33-412a-9878-612eb4c70e33.png)

**Comment by palinkas-jo-reggelt** [comment]
My best guess is it has something to do with your database settings. What database are you using and what connector?

**Comment by palinkas-jo-reggelt** [comment]
https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display

Have a look at this.

**Comment by asd014** [comment]
@palinkas-jo-reggelt thank you for the reply.

DB settings based on the config:
`$Database = array (
	'host'        => 'localhost',
	'username'    => 'myUsername',
	'password'    => 'myPassword',
	'dbname'      => 'MyDb',
	'driver'      => 'mysql',
	'port'        => '3306',
	'dsn'         => 'MySQL ODBC 5.3 ANSI Driver'
);
`

I've enable the php error and got this:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'mobilenumber' doesn't have a default value in C:\MyFolder\Files\hMail2FA\admin.php:72 Stack trace: #0 C:\MyFolder\Files\hMail2FA\admin.php(72): PDO->exec() #1 {main} thrown in C:\MyFolder\Files\hMail2FA\admin.php on line 72`

**Comment by palinkas-jo-reggelt** [comment]
Drop table hm_pw_change. Then in admin.php starting at line 60:

```
	$pdo->exec("
		CREATE TABLE IF NOT EXISTS hm_pw_change (
			accountid int(11) NOT NULL,
			mobilenumber varchar(10) DEFAULT NULL,
			altemail varchar(36) DEFAULT NULL,
			onetimecode int(6) NOT NULL DEFAULT 0,
			initpwchange datetime NOT NULL DEFAULT '1970-01-01 01:00:00',
			PRIMARY KEY (accountid)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	");

I'll update github later with this. Please let me know that it works. Thanks.
```

**Comment by asd014** [comment]
Thank you so much! It works perfectly.
